### ISSUE TITLE
ldc not auto detected

### ISSUE THREAD

**Issue by baruch** [dcarp/cmake-d#12]
I happened to install only ldc2 on my machine and cmake wouldn't auto detect it. I changed the auto-detect logic to search for it as well and it just works. Is there a reason why ldc2 wasn't added to the auto-detect?

**Comment by dcarp** [comment]
No reason that I know of, a PR is welcome.

**Comment by baruch** [comment]
I created a pull request for the change, a trivial one at that.

**Comment by dcarp** [comment]
Thanks!
