### ISSUE TITLE
CMAKE_SIZEOF_VOID_P not set

### ISSUE THREAD

**Issue by KingDuckZ** [dcarp/cmake-d#6]
The following D project won't work for me (cmake version 2.8.12.2):

 cmake_minimum_required(VERSION 2.6 FATAL_ERROR)
 set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/../cmake/Modules/cmake-d" "${CMAKE_MODULE_PATH}")
 project (test D)
 
 if (NOT CMAKE_SIZEOF_VOID_P)
         message(FATAL_ERROR "'CMAKE_SIZEOF_VOID_P' is undefined.")
 endif()

changing the line "project(test D)" to "project(test D C)" fixes the error but it shouldn't be necessary. According to the docs, CMAKE_SIZEOF_VOID_P gets set by the compiler testing step:
http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_SIZEOF_VOID_P.html

Edit: I only tested this with gdc/gcc on gentoo linux.

**Comment by Yoplitein** [comment]
You should try using [this fork of CMake](https://github.com/trentforkert/cmake) as it has more in-depth D support.

**Comment by KingDuckZ** [comment]
Do I understand correctly this issue has been closed as "fixed"? It still doesn't work for me:

    $ git rev-parse HEAD
    422e0a4d1cad1838890c19e6eb6219c42436f7d0
I tried both with gdc and ldc using the same cmake file I already posted:

    $ DC=ldc2 cmake ..
    -- The D compiler identification is LDC
    -- Check for working D compiler: /usr/bin/ldc2
    -- Check for working D compiler: /usr/bin/ldc2 -- works
    -- Detecting D compiler ABI info
    -- Detecting D compiler ABI info - failed
    CMake Error at CMakeLists.txt:6 (message):
      'CMAKE_SIZEOF_VOID_P' is undefined.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/michele/dev/code/d/magicdb/deleme/build/CMakeFiles/CMakeOutput.log".
    See also "/home/michele/dev/code/d/magicdb/deleme/build/CMakeFiles/CMakeError.log".

**Comment by dcarp** [comment]
Hopefully not it works! My test project was D and C :(
