### ISSUE TITLE
Error on OSX 

### ISSUE THREAD

**Issue by ZelimDamian** [dcarp/cmake-d#8]
On OSx 10.11.1 with CMake 3.3.2. Last time I checked there is the same error when this is run on a Windows machine.

DMD64 D Compiler v2.068
and
LDC - the LLVM D compiler (0.15.2): based on DMD v2.066.1 and LLVM 3.6.2

When running ```ccmake -DCMAKE_MODULE_PATH:PATH=../cmake-d ./build .``` in the tests directory, I get the following error:
```
CMake Error: Could not find cmake module file: CMakeDInformation.cmake

 CMake Error: Internal CMake error, TryCompile configure of cmake failed

 CMake Error at /Users/zelimdamian/Downloads/cmake-d-master
 2/cmake-d/CMakeTestDCompiler.cmake:45 (message):
   The D compiler "/usr/local/bin/dmd" is not able to compile a simple test
   program.

   It fails with the following output:



   CMake will not be able to correctly generate this project.
 Call Stack (most recent call first):
   CMakeLists.txt:7 (PROJECT)

**Comment by dcarp** [comment]
Can you provide full log of the error messages and the CMakeLists.txt file?

**Comment by ZelimDamian** [comment]
Sorry, the log above is all that CMake gives me. The CMakeLists.txt is the one in this repo's ```tests``` directory: https://github.com/dcarp/cmake-d/tree/master/tests

After a bit of digging it seems that there are only Linux and Windows ```.cmake``` files in the ```Platforms``` directory. Do the Linux ones cover OSx as well?

**Comment by ZelimDamian** [comment]
I figured out that the ```CMakeTestDCompiler.cmake``` file is trying to compile a simple HelloWorld of a sort. I copied the code into a separate ```test.d``` file:
``` d
int main(char[][] args) {
  return args.sizeof-1;
}
```
It compiles and runs without any problem with ``` dmd test.d && ./test```

Why would it report a failure to compile?

**Comment by ZelimDamian** [comment]
It seems that this problem just went away. It may have been a directory permissions issue. There are now other problems though. Will open a separate issue.
