### ISSUE TITLE
Error while detecting compiler on Travis Ubuntu Linux

### ISSUE THREAD

**Issue by JohanEngelen** [dcarp/cmake-d#9]
See the error message here:
https://api.travis-ci.org/jobs/102711636/log.txt?deansi=true

CMakeLists.txt:
```
cmake_minimum_required(VERSION 2.8)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/Modules")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/cmake-d")
project(ldc C CXX D)
```

@dcarp Hi, are you still maintaining cmake-d?
I'd like to use cmake-d for LDC's Travis tests, but it seems that it does not work on Travis with Ubuntu (it works fine locally on Windows, OS X, and Ubuntu 14, without sudo).
Thanks for the help.

**Comment by dcarp** [comment]
How your .travis.yml looks like?
It seams that cmake tries to use the D compiler module from the cmake system path, but you specified to be cmake/cmake-d in your source directory.

**Comment by JohanEngelen** [comment]
I have simplified our setup and removed the dependency on cmake-d. I felt it was creating more problems than it solved, mostly because of mixed C/C++/D code.
Because I've rebased+squashed, I no longer have the CMakeLists.txt with cmake-d dependency, I'm sorry.
The .travis.yml looked like this:
https://github.com/ldc-developers/ldc/blob/bcbc02b304b69a071abe5bab699af6cb9942e10b/.travis.yml
